"""init

Revision ID: 02fee3cb5ab3
Revises: 
Create Date: 2025-05-26 11:14:51.760446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02fee3cb5ab3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clienti',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=128), nullable=False),
    sa.Column('codice', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('indirizzo', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clienti', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clienti_codice'), ['codice'], unique=True)
        batch_op.create_index(batch_op.f('ix_clienti_nome'), ['nome'], unique=False)

    op.create_table('corso_sicurezza',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titolo', sa.String(length=100), nullable=False),
    sa.Column('descrizione', sa.Text(), nullable=True),
    sa.Column('durata_ore', sa.Integer(), nullable=True),
    sa.Column('data_scadenza', sa.Date(), nullable=True),
    sa.Column('is_completato', sa.Boolean(), nullable=True),
    sa.Column('data_completamento', sa.DateTime(), nullable=True),
    sa.Column('archiviato', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fornitori',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=128), nullable=False),
    sa.Column('codice', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('indirizzo', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fornitori', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fornitori_codice'), ['codice'], unique=True)
        batch_op.create_index(batch_op.f('ix_fornitori_nome'), ['nome'], unique=False)

    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=128), nullable=False),
    sa.Column('taglia', sa.String(length=64), nullable=True),
    sa.Column('quantita', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('modules', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('competenza',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=64), nullable=False),
    sa.Column('descrizione', sa.Text(), nullable=True),
    sa.Column('livello', sa.String(length=20), nullable=True),
    sa.Column('area', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('corso_formazione',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titolo', sa.String(length=100), nullable=False),
    sa.Column('descrizione', sa.Text(), nullable=True),
    sa.Column('durata_ore', sa.Integer(), nullable=True),
    sa.Column('giorno_inizio', sa.Date(), nullable=True),
    sa.Column('giorno_fine', sa.Date(), nullable=True),
    sa.Column('scadenza_relativa', sa.String(length=50), nullable=True),
    sa.Column('is_obbligatorio', sa.Boolean(), nullable=True),
    sa.Column('archiviato', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dati_excel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_file', sa.String(length=128), nullable=False),
    sa.Column('descrizione', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dipendente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cognome', sa.String(length=100), nullable=False),
    sa.Column('data_nascita', sa.Date(), nullable=False),
    sa.Column('luogo_nascita', sa.String(length=100), nullable=False),
    sa.Column('provincia_nascita', sa.String(length=2), nullable=False),
    sa.Column('codice_fiscale', sa.String(length=16), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('matricola', sa.String(length=20), nullable=True),
    sa.Column('reparto', sa.String(length=100), nullable=True),
    sa.Column('ruolo', sa.String(length=100), nullable=True),
    sa.Column('data_assunzione_somministrazione', sa.Date(), nullable=True),
    sa.Column('agenzia_somministrazione', sa.String(length=100), nullable=True),
    sa.Column('data_assunzione_indeterminato', sa.Date(), nullable=True),
    sa.Column('legge_104', sa.Boolean(), nullable=True),
    sa.Column('donatore_avis', sa.Boolean(), nullable=True),
    sa.Column('indirizzo_residenza', sa.String(length=200), nullable=True),
    sa.Column('citta_residenza', sa.String(length=100), nullable=True),
    sa.Column('provincia_residenza', sa.String(length=2), nullable=True),
    sa.Column('cap_residenza', sa.String(length=5), nullable=True),
    sa.Column('data_cessazione', sa.Date(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('archiviato', sa.Boolean(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricola')
    )
    op.create_table('fatturati',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('importo', sa.Float(), nullable=False),
    sa.Column('descrizione', sa.Text(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clienti.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fatturati', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fatturati_data'), ['data'], unique=False)

    op.create_table('modulo1_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valore_numerico', sa.Float(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('viewed', sa.Boolean(), nullable=True),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.Column('viewed_by_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['viewed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modulo4_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titolo', sa.String(length=128), nullable=False),
    sa.Column('valore1', sa.Float(), nullable=True),
    sa.Column('valore2', sa.Float(), nullable=True),
    sa.Column('valore3', sa.Float(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('pdf_path', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modulo5_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valore_numerico', sa.Float(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('viewed', sa.Boolean(), nullable=True),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.Column('viewed_by_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['viewed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modulo6_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valore1', sa.Float(), nullable=False),
    sa.Column('valore2', sa.Float(), nullable=True),
    sa.Column('valore3', sa.Float(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('viewed', sa.Boolean(), nullable=True),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modulo7_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valore1', sa.Float(), nullable=False),
    sa.Column('valore2', sa.Float(), nullable=True),
    sa.Column('valore3', sa.Float(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('viewed', sa.Boolean(), nullable=True),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('richiesta_permesso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dipendente_id', sa.Integer(), nullable=False),
    sa.Column('data_inizio', sa.Date(), nullable=False),
    sa.Column('data_fine', sa.Date(), nullable=False),
    sa.Column('ore', sa.Float(), nullable=False),
    sa.Column('motivo', sa.String(length=500), nullable=False),
    sa.Column('stato', sa.String(length=20), nullable=True),
    sa.Column('data_richiesta', sa.DateTime(), nullable=True),
    sa.Column('approvato_da', sa.Integer(), nullable=True),
    sa.Column('data_approvazione', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approvato_da'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dipendente_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spese',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('importo', sa.Float(), nullable=False),
    sa.Column('descrizione', sa.Text(), nullable=True),
    sa.Column('fornitore_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fornitore_id'], ['fornitori.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('spese', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spese_data'), ['data'], unique=False)

    op.create_table('course_completion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('dipendente_id', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['training_course.id'], ),
    sa.ForeignKeyConstraint(['dipendente_id'], ['dipendente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dipendente_competenza',
    sa.Column('dipendente_id', sa.Integer(), nullable=False),
    sa.Column('competenza_id', sa.Integer(), nullable=False),
    sa.Column('percentuale', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['competenza_id'], ['competenza.id'], ),
    sa.ForeignKeyConstraint(['dipendente_id'], ['dipendente.id'], ),
    sa.PrimaryKeyConstraint('dipendente_id', 'competenza_id')
    )
    op.create_table('dipendente_corso_sicurezza',
    sa.Column('dipendente_id', sa.Integer(), nullable=False),
    sa.Column('corso_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['corso_id'], ['corso_sicurezza.id'], ),
    sa.ForeignKeyConstraint(['dipendente_id'], ['dipendente.id'], ),
    sa.PrimaryKeyConstraint('dipendente_id', 'corso_id')
    )
    op.create_table('modulo1_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=128), nullable=False),
    sa.Column('path', sa.String(length=256), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['modulo1_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modulo5_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=128), nullable=False),
    sa.Column('path', sa.String(length=256), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['modulo5_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partecipazione_corso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dipendente_id', sa.Integer(), nullable=False),
    sa.Column('corso_id', sa.Integer(), nullable=False),
    sa.Column('stato', sa.String(length=20), nullable=True),
    sa.Column('data_iscrizione', sa.DateTime(), nullable=True),
    sa.Column('data_completamento', sa.DateTime(), nullable=True),
    sa.Column('valutazione', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['corso_id'], ['corso_formazione.id'], ),
    sa.ForeignKeyConstraint(['dipendente_id'], ['dipendente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dipendente_id', sa.Integer(), nullable=False),
    sa.Column('competenza_id', sa.Integer(), nullable=False),
    sa.Column('valutazione', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['competenza_id'], ['competenza.id'], ),
    sa.ForeignKeyConstraint(['dipendente_id'], ['dipendente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prelievi_vestiario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dipendente_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantita', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('data_prelievo', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dipendente_id'], ['dipendente.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['inventory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('record_excel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('colonna1', sa.String(length=128), nullable=True),
    sa.Column('colonna2', sa.String(length=128), nullable=True),
    sa.Column('colonna3', sa.Float(), nullable=True),
    sa.Column('colonna4', sa.Float(), nullable=True),
    sa.Column('colonna5', sa.DateTime(), nullable=True),
    sa.Column('colonna6', sa.String(length=256), nullable=True),
    sa.Column('dati_excel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dati_excel_id'], ['dati_excel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('residuo_ferie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dipendente_id', sa.Integer(), nullable=False),
    sa.Column('anno', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('ore_totali', sa.Float(), nullable=False),
    sa.Column('ore_usate', sa.Float(), nullable=True),
    sa.Column('ore_residue', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['dipendente_id'], ['dipendente.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dipendente_id', 'anno', 'tipo', name='unique_residuo')
    )
    op.create_table('richiesta_ferie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dipendente_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('data_inizio', sa.Date(), nullable=False),
    sa.Column('data_fine', sa.Date(), nullable=False),
    sa.Column('ore', sa.Float(), nullable=False),
    sa.Column('stato', sa.String(length=20), nullable=True),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('data_richiesta', sa.DateTime(), nullable=True),
    sa.Column('approvato_da', sa.Integer(), nullable=True),
    sa.Column('data_approvazione', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approvato_da'], ['users.id'], name='fk_richiesta_ferie_approvato_da'),
    sa.ForeignKeyConstraint(['dipendente_id'], ['dipendente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timbrature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dipendente_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('modificato_da', sa.Integer(), nullable=True),
    sa.Column('data_modifica', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dipendente_id'], ['dipendente.id'], name='fk_timbratura_dipendente'),
    sa.ForeignKeyConstraint(['modificato_da'], ['users.id'], name='fk_timbratura_modificatore'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timbrature')
    op.drop_table('richiesta_ferie')
    op.drop_table('residuo_ferie')
    op.drop_table('record_excel')
    op.drop_table('prelievi_vestiario')
    op.drop_table('performance')
    op.drop_table('partecipazione_corso')
    op.drop_table('modulo5_photos')
    op.drop_table('modulo1_photos')
    op.drop_table('dipendente_corso_sicurezza')
    op.drop_table('dipendente_competenza')
    op.drop_table('course_completion')
    with op.batch_alter_table('spese', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spese_data'))

    op.drop_table('spese')
    op.drop_table('richiesta_permesso')
    op.drop_table('modulo7_entries')
    op.drop_table('modulo6_entries')
    op.drop_table('modulo5_entries')
    op.drop_table('modulo4_entries')
    op.drop_table('modulo1_entries')
    with op.batch_alter_table('fatturati', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fatturati_data'))

    op.drop_table('fatturati')
    op.drop_table('dipendente')
    op.drop_table('dati_excel')
    op.drop_table('corso_formazione')
    op.drop_table('competenza')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('training_course')
    op.drop_table('inventory')
    with op.batch_alter_table('fornitori', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fornitori_nome'))
        batch_op.drop_index(batch_op.f('ix_fornitori_codice'))

    op.drop_table('fornitori')
    op.drop_table('corso_sicurezza')
    with op.batch_alter_table('clienti', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clienti_nome'))
        batch_op.drop_index(batch_op.f('ix_clienti_codice'))

    op.drop_table('clienti')
    # ### end Alembic commands ###
