"""aggiungi data_prelievo a prelievi_vestiario

Revision ID: 7f2956d4a14f
Revises: 36260ef865ea
Create Date: 2025-05-23 14:40:18.619707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f2956d4a14f'
down_revision = '36260ef865ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prelievi_vestiario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_prelievo', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.drop_constraint('uq_users_email', type_='unique')
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_unique_constraint('uq_users_email', ['email'])
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)

    with op.batch_alter_table('prelievi_vestiario', schema=None) as batch_op:
        batch_op.drop_column('data_prelievo')

    # ### end Alembic commands ###
