"""Update_CorsoFormazione_fields_for_giorni_and_scadenza_relativa

Revision ID: ad921d547604
Revises: bcdff6b0227d
Create Date: 2025-05-21 16:31:46.771269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad921d547604'
down_revision = 'bcdff6b0227d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('corso_formazione', schema=None) as batch_op:
        batch_op.add_column(sa.Column('giorno_inizio', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('giorno_fine', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('scadenza_relativa', sa.String(length=50), nullable=True))
        batch_op.drop_column('data_scadenza')
        batch_op.drop_column('data_fine')
        batch_op.drop_column('data_inizio')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('corso_formazione', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_inizio', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('data_fine', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('data_scadenza', sa.DATE(), nullable=True))
        batch_op.drop_column('scadenza_relativa')
        batch_op.drop_column('giorno_fine')
        batch_op.drop_column('giorno_inizio')

    # ### end Alembic commands ###
