"""init

Revision ID: cfdb6c1a2bb5
Revises: 
Create Date: 2025-05-27 16:17:49.598841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfdb6c1a2bb5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dpi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descrizione', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('categoria', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('fornitore', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('codice', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('data_acquisto', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('data_scadenza', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dpi', schema=None) as batch_op:
        batch_op.drop_column('data_scadenza')
        batch_op.drop_column('data_acquisto')
        batch_op.drop_column('codice')
        batch_op.drop_column('fornitore')
        batch_op.drop_column('categoria')
        batch_op.drop_column('descrizione')

    # ### end Alembic commands ###
